from .kd import KnowledgeDistillationKDLoss, knowledge_distillation_kl_div_loss
from .dkd import KnowledgeDistillationDKDLoss, knowledge_distillation_dkd_loss
from .gdkd import KnowledgeDistillationGDKDLoss, knowledge_distillation_gdkd_loss
from .dist import KnowledgeDistillationDISTLoss, knowledge_distillation_dist_loss